### ISSUE TITLE
Kullanıcı adı ve parola bilgileri

### ISSUE THREAD

**Issue by angelside** [phpuzem/netgsm#1]
Kullanıcı adı ve parola bilgilerini bu şekilde bir ayar dosyasında tutmak güvenlik zafiyeti oluşturmaz mı? NetGSM api sisteminde API key yok sanırım?

**Comment by phpuzem** [comment]
Evet netgsm üzerinde herhangi bir hash mevcut değil, sistem xml post, soap gibi işlemler üzerinden gitmekte. Config dosyası konusuna gelince bir zaafiyet oluşmayacaktır.
